const arr = (v) => Array.isArray(v) ? v : [];
const clean = (v, n = 180) => String(v || '').trim().replace(/\s+/g, ' ').slice(0, n);
const key = (v) => String(v || '').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '');
const uniq = (xs) => [...new Set(arr(xs).filter(Boolean).map(String))];

function usageOf(u = {}) { const prompt=Number(u.prompt_tokens||u.input_tokens||0), completion=Number(u.completion_tokens||u.output_tokens||0); return {prompt,completion,total:Number(u.total_tokens||prompt+completion)}; }
function addUsage(t,u){t.prompt+=u.prompt;t.completion+=u.completion;t.total+=u.total;}
function parseJson(text){ try{return {value:JSON.parse(text||'{}'),error:''};}catch(e){return {value:{},error:e.message||'invalid JSON'};} }
function friendlyName(name){const v=clean(name,100);return !!v && !/[.#/:()]/.test(v) && !/\b(service|services|record|records|result|results|output|retrieved|read\/updated)\b/i.test(v);}

function workflowCatalog(arcs,mapStateForArc,snapshot){return arcs.map(a=>({id:a.id,name:clean(a.title,110),description:clean(a.businessIntent||a.outcome||a.businessOutcome||a.nature,150),state:mapStateForArc(a,snapshot)})).slice(0,40);}
function entityCatalog(arcs){const by=new Map();for(const a of arcs){for(const d of arr(a.entityDetails)){const name=clean(d?.name,100);if(!friendlyName(name))continue;const k=key(name),cur=by.get(k)||{name,description:'',fieldCount:0};if(!cur.description&&d?.description)cur.description=clean(d.description,130);cur.fieldCount=Math.max(cur.fieldCount,arr(d?.fields).length);by.set(k,cur);}for(const raw of arr(a.entities)){const name=clean(raw,100);if(!friendlyName(name))continue;const k=key(name);if(!by.has(k))by.set(k,{name,description:'',fieldCount:0});}}return [...by.values()].slice(0,80);}
function fieldScore(f,q){const words=String(q||'').toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2),hay=`${f?.name||''} ${f?.description||''}`.toLowerCase();let s=f?.isPk?2:0;for(const w of words)if(hay.includes(w))s+=2;if(/orderid|partyid|productid|contactmechid|seqid/i.test(f?.name||''))s+=2;if(/quantity|amount|total|price|date|status|region|state|country|geo/i.test(hay))s+=1;return s;}
function fieldsForEntity(entityName,arcs,q,limit=14){const wanted=key(entityName),by=new Map();for(const a of arcs)for(const d of arr(a.entityDetails)){if(key(d?.name)!==wanted)continue;for(const f of arr(d?.fields)){const entity=clean(f?.sourceEntity||d?.name||entityName,100),name=clean(f?.physicalFieldName||f?.name,100);if(!name)continue;const fk=`${key(entity)}|${key(name)}`;if(!by.has(fk))by.set(fk,{entity,name,type:clean(f?.type,50),description:clean(f?.description,100),isPk:!!f?.isPk,score:fieldScore(f,q)});}}return [...by.values()].sort((a,b)=>b.score-a.score).slice(0,limit).map(({score,...f})=>f);}
function relationEdges(arcs){const out=[];for(const a of arcs)for(const r of arr(a.relationshipDetails)){const from=clean(r?.from,100),to=clean(r?.to,100);if(friendlyName(from)&&friendlyName(to))out.push({from,to,relation:clean(r?.relation,100),description:clean(r?.description,120),workflowId:a.id});}return out;}
function entityDetail(name,arcs,q){const wanted=key(name);let description='';const workflows=[];for(const a of arcs){const d=arr(a.entityDetails).find(x=>key(x?.name)===wanted),present=d||arr(a.entities).some(e=>key(e)===wanted)||arr(a.persistentObjects).some(e=>key(e)===wanted);if(!present)continue;if(!description&&d?.description)description=clean(d.description,140);workflows.push({id:a.id,name:clean(a.title,90)});}return{name,description,fields:fieldsForEntity(name,arcs,q),workflows:workflows.slice(0,4)};}
function selectedWorkflowDetail(ids,arcs){const wanted=new Set(arr(ids).map(String));return arcs.filter(a=>wanted.has(String(a.id))).slice(0,5).map(a=>({id:a.id,name:clean(a.title,100),description:clean(a.businessIntent||a.outcome,130),relations:arr(a.relationshipDetails).filter(r=>friendlyName(r?.from)&&friendlyName(r?.to)).slice(0,10).map(r=>({from:r.from,relation:r.relation,to:r.to}))}));}
function nearbyEntities(selected,edges,limit=8){const wanted=new Set(arr(selected).map(key)),out=[];for(const e of edges){if(wanted.has(key(e.from))&&!wanted.has(key(e.to)))out.push(e.to);if(wanted.has(key(e.to))&&!wanted.has(key(e.from)))out.push(e.from);}return uniq(out).filter(friendlyName).slice(0,limit);}
function sameNamedJoinFields(a,b){const out=[];for(const lf of arr(a.fields))for(const rf of arr(b.fields)){if(lf.name&&rf.name&&key(lf.name)===key(rf.name)&&/id$|seqid$/i.test(lf.name))out.push({left:`${a.name}.${lf.name}`,right:`${b.name}.${rf.name}`,basis:'matching identifier fields',evidenced:true});}return out.slice(0,4);}
function findEntityPath(from,to,edges,maxDepth=4){const start=key(from),target=key(to);if(!start||!target)return null;const q=[{name:from,path:[]}],seen=new Set([start]);while(q.length){const cur=q.shift();if(cur.path.length>=maxDepth)continue;for(const e of edges){let next=null,edge=null;if(key(e.from)===key(cur.name)){next=e.to;edge=e;}else if(key(e.to)===key(cur.name)){next=e.from;edge={...e,from:e.to,to:e.from};}if(!next||seen.has(key(next)))continue;const path=[...cur.path,edge];if(key(next)===target)return path;seen.add(key(next));q.push({name:next,path});}}return null;}
function connectSelectedEntities(names,arcs,q){const edges=relationEdges(arcs),details=new Map(arr(names).map(n=>[key(n),entityDetail(n,arcs,q)])),connections=[];for(let i=0;i<names.length;i++)for(let j=i+1;j<names.length;j++){const a=names[i],b=names[j],da=details.get(key(a)),db=details.get(key(b)),fieldJoins=da&&db?sameNamedJoinFields(da,db):[],path=findEntityPath(a,b,edges);if(fieldJoins.length||path)connections.push({from:a,to:b,fieldJoins,semanticPath:path||[]});}return connections.slice(0,10);}

async function jsonCall(client,model,system,payload,maxTokens,log,stage,usage){const completion=await client.chat.completions.create({model,messages:[{role:'system',content:system},{role:'user',content:JSON.stringify(payload)}],response_format:{type:'json_object'},temperature:0,max_tokens:maxTokens});const u=usageOf(completion.usage||{});addUsage(usage,u);const raw=completion.choices?.[0]?.message?.content||'',finishReason=completion.choices?.[0]?.finish_reason||'',parsed=parseJson(raw);log('query_guided_stage',{stage,input:payload,output:parsed.value,rawOutput:raw,parseError:parsed.error,finishReason,usage:u});return parsed.value;}

export async function investigateQuery({question,client,model,arcs,snapshot,mapStateForArc,pathHints=()=>[],log=()=>{}}){const usage={prompt:0,completion:0,total:0},workflows=workflowCatalog(arcs,mapStateForArc,snapshot),entities=entityCatalog(arcs);
 const scope=await jsonCall(client,model,'Select the smallest relevant semantic area. Return ONLY compact JSON with keys intent, workflowIds, entities, needs. workflowIds max 5; entities max 6; needs max 6 short strings. Use only supplied names/ids.',{question,workflows,entities},900,log,'scope',usage);
 const selectedWorkflowIds=arr(scope.workflowIds).map(String).slice(0,5),selectedEntities=uniq(arr(scope.entities).filter(n=>entities.some(e=>key(e.name)===key(n)))).slice(0,6),edges=relationEdges(arcs),neighborhood=nearbyEntities(selectedEntities,edges,8),evidenceNames=uniq([...selectedEntities,...neighborhood]).slice(0,10);
 const evidence={question,intent:scope.intent||'',needs:arr(scope.needs).slice(0,6),workflows:selectedWorkflowDetail(selectedWorkflowIds,arcs),entities:evidenceNames.map(n=>entityDetail(n,arcs,question)),relations:edges.filter(e=>evidenceNames.some(n=>key(n)===key(e.from)||key(n)===key(e.to))).slice(0,18)};
 const plan=await jsonCall(client,model,'Choose exact data needed. Return ONLY compact JSON with keys grain, entities, fields, connections, missing. fields entries: entity, field, role. Max 5 entities, 8 fields, 5 connections, 5 missing strings. Every name must exist in evidence. Include visible join keys.',evidence,1000,log,'plan',usage);
 const plannedEntities=uniq(arr(plan.entities).filter(n=>evidenceNames.some(e=>key(e)===key(n)))).slice(0,5),connections=connectSelectedEntities(plannedEntities,arcs,question),plannedFields=arr(plan.fields).filter(f=>{const d=evidence.entities.find(e=>key(e.name)===key(f?.entity));return d&&arr(d.fields).some(x=>key(x.name)===key(f?.field));}).slice(0,8);
 const packet={question,intent:scope.intent||'other',grain:clean(plan.grain,140),fields:plannedFields,connections,missing:arr(plan.missing).slice(0,5),selectedEntities:plannedEntities,unlearnedHints:pathHints(question).slice(0,2).map(h=>({id:h.id||h.pathId,label:clean(h.workflowTitle||h.label,90)}))};
 const answer=await jsonCall(client,model,'Return ONLY compact JSON: intent, answer, dataView, nextStep. answer max 3 sentences. dataView has grain, select, joins, filters, groupBy, orderBy, missing. Use only packet fields. Exact field joins from fieldJoins are evidenced=true; semantic-only paths are evidenced=false. Keep arrays short. Never expose source paths or framework/service names.',packet,1200,log,'answer',usage);
 return{...answer,investigation:{mode:'guided',stages:3,selectedWorkflowIds,selectedEntities:plannedEntities,usage}};
}
